name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    # steps:
    # - uses: actions/checkout@v4
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: jipodhead/openai-cti-summarizer
      - name : Set env variables
        run: |
          VERSION=${{ env.VERSION }}
          echo $VERSION
          USE_MS_AZURE=${{ env.USE_MS_AZURE }}
          OPENAI_API_KEY=${{ env.OPENAI_API_KEY }}
          echo "VERSION=$VERSION" > .env
          echo "USE_MS_AZURE=$USE_MS_AZURE" >> .env
          echo "OPENAI_API_KEY=$OPENAI_API_KEY" >> .env
          cat .env


      - name: Build and push Docker image
        id: push
        # ..... >>  Env variables could also be set here << .....
        # i think tho, that this is not needed and so i created the job above that creates a env file, so this still works manually
        # otherwise i would need to remove the line from the dockerfile
        # all the stuff in the dockerfile could be moved to the job above

        # env: 
        #   OPENAI_API_KEY: ${{ env.OPENAI_API_KEY }}
        #   USE_MS_AZURE: ${{ env.USE_MS_AZURE }}
        #   VERSION: ${{ env.VERSION }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: jipodhead/openai-cti-summarizer:latest
